# [作業目標]

1. [簡答題] 請問下列兩種將 Array 轉換成 List 的方式有何不同？

```
print('list(a): ', list(a))
print('tolist(): ', a.tolist())
```

2. 請試著在程式中印出以下三個 NdArray 的屬性？（屬性：ndim、shape、size、dtype、itemsize、length、type）

```
a = np.random.randint(10, size=6) 
b = np.random.randint(10, size=(3,4)) 
c = np.random.randint(10, size=(2,3,2)) 
```

3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


# 作業 

### 1. [簡答題] 請問下列兩種將 Array 轉換成 List 的方式有何不同？

```
print('list(a): ', list(a))
print('tolist(): ', a.tolist())
```


In [6]:
import numpy as np
a=np.random.randint(10,size=6)
print(a)
print(type(a))
print('list(a): ', list(a))
print('tolist(): ', a.tolist())

[9 3 5 6 9 0]
<class 'numpy.ndarray'>
list(a):  [9, 3, 5, 6, 9, 0]
tolist():  [9, 3, 5, 6, 9, 0]


In [13]:
b = np.random.randint(10, size=6).reshape(3,2)
print(b)
print(type(b))
print('list(b): ', list(b))
print(type(list(b)))
print('b.tolist(): ', b.tolist())
print(type(b.tolist()))

[[5 4]
 [2 1]
 [9 2]]
<class 'numpy.ndarray'>
list(b):  [array([5, 4]), array([2, 1]), array([9, 2])]
<class 'list'>
b.tolist():  [[5, 4], [2, 1], [9, 2]]
<class 'list'>


Ans:
list中的元素只有第一層轉換為list,元素則為原本型態\
tolist則將整個array以及其中元素,都轉換成list


### 2. 請試著在程式中印出以下三個 NdArray 的屬性並且解釋結果？（屬性：ndim、shape、size、dtype、itemsize、length、type）

```
a = np.random.randint(10, size=6) 
b = np.random.randint(10, size=(3,4)) 
c = np.random.randint(10, size=(2,3,2)) 
```

In [14]:
# 記得先 Import 正確的套件
a = np.random.randint(10, size=6) 
print(a)
print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)
print(a.itemsize)
print(len(a))
print(type(a))

[6 7 1 6 8 7]
1
(6,)
6
int32
4
6
<class 'numpy.ndarray'>


In [15]:
b = np.random.randint(10, size=(3,4)) 
print(b)
print(b.ndim)
print(b.shape)
print(b.size)
print(b.dtype)
print(b.itemsize)
print(len(b))
print(type(b))

[[7 7 9 9]
 [3 9 6 4]
 [0 7 9 8]]
2
(3, 4)
12
int32
4
3
<class 'numpy.ndarray'>


In [16]:
c = np.random.randint(10, size=(2,3,2)) 
print(c)
print(c.ndim)
print(c.shape)
print(c.size)
print(c.dtype)
print(c.itemsize)
print(len(c))
print(type(c))

[[[3 9]
  [7 8]
  [8 5]]

 [[0 1]
  [8 5]
  [6 3]]]
3
(2, 3, 2)
12
int32
4
2
<class 'numpy.ndarray'>


### 3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


In [17]:
a = np.random.randint(10, size=6) 

print(a.tolist())
print(list(a))


[1, 9, 2, 1, 9, 5]
[1, 9, 2, 1, 9, 5]


In [18]:
b = np.random.randint(10, size=(3,4)) 

print(b.tolist())
print(list(b))


[[3, 9, 3, 4], [2, 4, 8, 2], [0, 2, 9, 8]]
[array([3, 9, 3, 4]), array([2, 4, 8, 2]), array([0, 2, 9, 8])]


In [19]:
c = np.random.randint(10, size=(2,3,2)) 

print(c.tolist())
print(list(c))


[[[2, 7], [7, 1], [7, 8]], [[7, 1], [0, 0], [4, 8]]]
[array([[2, 7],
       [7, 1],
       [7, 8]]), array([[7, 1],
       [0, 0],
       [4, 8]])]


In [22]:
def tolist(iterable):
    if type(iterable) != np.ndarray:
        return iterable
    new = []
    for obj in iterable:
        new.append(tolist(obj))
    return list(new)

print(tolist(a))
print(tolist(b))
print(tolist(c))

[1, 9, 2, 1, 9, 5]
[[3, 9, 3, 4], [2, 4, 8, 2], [0, 2, 9, 8]]
[[[2, 7], [7, 1], [7, 8]], [[7, 1], [0, 0], [4, 8]]]


In [21]:
def tolist(iterable):
    if type(iterable) != np.ndarray:
        return iterable
    return [tolist(obj) for obj in iterable]

print(tolist(a))
print(tolist(b))
print(tolist(c))

[1, 9, 2, 1, 9, 5]
[[3, 9, 3, 4], [2, 4, 8, 2], [0, 2, 9, 8]]
[[[2, 7], [7, 1], [7, 8]], [[7, 1], [0, 0], [4, 8]]]
